// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STBEverywhere_Back_SharedModels.Data;

#nullable disable

namespace STBEverywhere_Back_SharedModels.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250303152419_Addemail")]
    partial class Addemail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Carte", b =>
                {
                    b.Property<string>("NumCarte")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CodeCVV")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("CodePIN")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateRecuperation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Iddemande")
                        .HasColumnType("int");

                    b.Property<string>("NomCarte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Plafond")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RIB")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TypeCarte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("NumCarte");

                    b.HasIndex("Iddemande");

                    b.HasIndex("RIB");

                    b.ToTable("Cartes");

                    b.HasData(
                        new
                        {
                            NumCarte = "1111222233334444",
                            CodeCVV = 123,
                            CodePIN = 1234,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateExpiration = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Iddemande = 1,
                            NomCarte = "Visa",
                            Plafond = 1000m,
                            RIB = "12345678923537902652",
                            Statut = "Active",
                            TypeCarte = "International"
                        },
                        new
                        {
                            NumCarte = "5555666677778888",
                            CodeCVV = 153,
                            CodePIN = 1534,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateExpiration = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Iddemande = 2,
                            NomCarte = "Mastercard",
                            Plafond = 1000m,
                            RIB = "65432110223463790345",
                            Statut = "active",
                            TypeCarte = "National"
                        });
                });

            modelBuilder.Entity("DemandeCarte", b =>
                {
                    b.Property<int>("Iddemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EmailEnvoye")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomCarte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumCompte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NumTel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TypeCarte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Iddemande");

                    b.HasIndex("ClientId");

                    b.ToTable("DemandesCarte");

                    b.HasData(
                        new
                        {
                            Iddemande = 1,
                            CIN = "14668061",
                            ClientId = 1,
                            DateCreation = new DateTime(2025, 3, 3, 15, 24, 19, 253, DateTimeKind.Local).AddTicks(8620),
                            Email = "john.doe@example.com",
                            EmailEnvoye = false,
                            NomCarte = "Visa",
                            NumCompte = "12345678923537902652",
                            NumTel = "12345678",
                            Statut = "DisponibleAgence",
                            TypeCarte = "International"
                        },
                        new
                        {
                            Iddemande = 2,
                            CIN = "14668062",
                            ClientId = 2,
                            DateCreation = new DateTime(2025, 3, 3, 15, 24, 19, 253, DateTimeKind.Local).AddTicks(8706),
                            Email = "jane.smith@example.com",
                            EmailEnvoye = false,
                            NomCarte = "Mastercard",
                            NumCompte = "65432110223463790345",
                            NumTel = "87654321",
                            Statut = "DisponibleAgence",
                            TypeCarte = "National"
                        });
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Civilite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EtatCivil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationalite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumCIN")
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "123 Main St",
                            Civilite = "M",
                            DateNaissance = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            EtatCivil = "Célibataire",
                            MotDePasse = "$2a$11$Qgg8emDgvYRbsNSFVCHF0ebh1C4kROLPxWwNq18k4X6Ef3.lDXhxG",
                            Nationalite = "US",
                            Nom = "Doe",
                            NumCIN = "14668061",
                            Prenom = "John",
                            Residence = "New York",
                            Telephone = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "456 Elm St",
                            Civilite = "Mme",
                            DateNaissance = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            EtatCivil = "Marié(e)",
                            MotDePasse = "$2a$11$ThHY6X3G6KImzE1gNCGqN.Ej.knq26wThiUP6A80dDamNRGL3LwBy",
                            Nationalite = "CA",
                            Nom = "Smith",
                            NumCIN = "14668062",
                            Prenom = "Jane",
                            Residence = "Toronto",
                            Telephone = "987654321"
                        });
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Compte", b =>
                {
                    b.Property<string>("RIB")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumCin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Solde")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RIB");

                    b.HasIndex("ClientId");

                    b.ToTable("Comptes");

                    b.HasData(
                        new
                        {
                            RIB = "12345678923537902652",
                            ClientId = 1,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumCin = "14668061",
                            Solde = 1000.50m,
                            Statut = "Actif",
                            Type = "Courant"
                        },
                        new
                        {
                            RIB = "65432110223463790345",
                            ClientId = 1,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumCin = "14668062",
                            Solde = 5000.00m,
                            Statut = "Actif",
                            Type = "Épargne"
                        });
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Virement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateVirement")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RIB_Emetteur")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RIB_Recepteur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RIB_Emetteur", "DateVirement")
                        .IsUnique();

                    b.ToTable("Virements");
                });

            modelBuilder.Entity("Carte", b =>
                {
                    b.HasOne("DemandeCarte", "DemandeCarte")
                        .WithMany()
                        .HasForeignKey("Iddemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STBEverywhere_Back_SharedModels.Compte", "Compte")
                        .WithMany("Cartes")
                        .HasForeignKey("RIB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");

                    b.Navigation("DemandeCarte");
                });

            modelBuilder.Entity("DemandeCarte", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Client", "Client")
                        .WithMany("DemandesCarte")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Compte", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Client", "Client")
                        .WithMany("Comptes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Client", b =>
                {
                    b.Navigation("Comptes");

                    b.Navigation("DemandesCarte");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Compte", b =>
                {
                    b.Navigation("Cartes");
                });
#pragma warning restore 612, 618
        }
    }
}
