// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STBEverywhere_Back_SharedModels.Data;

#nullable disable

namespace STBEverywhere_Back_SharedModels.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250414130534_globalmigration")]
    partial class globalmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DemandeCarte", b =>
                {
                    b.Property<int>("Iddemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("CarteAjouter")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EmailEnvoye")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EmailEnvoyeLivree")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomCarte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumCompte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RIB");

                    b.Property<string>("NumTel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeCarte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Iddemande");

                    b.HasIndex("NumCompte");

                    b.ToTable("DemandesCarte");

                    b.HasData(
                        new
                        {
                            Iddemande = 1,
                            CIN = "14668061",
                            CarteAjouter = false,
                            DateCreation = new DateTime(2025, 4, 14, 14, 5, 33, 320, DateTimeKind.Local).AddTicks(2570),
                            Email = "john.doe@example.com",
                            EmailEnvoye = false,
                            EmailEnvoyeLivree = false,
                            NomCarte = "VisaClassic",
                            NumCompte = "12345678923537902652",
                            NumTel = "12345678",
                            Statut = "DisponibleEnAgence",
                            TypeCarte = "International"
                        },
                        new
                        {
                            Iddemande = 2,
                            CIN = "14668062",
                            CarteAjouter = false,
                            DateCreation = new DateTime(2025, 4, 14, 14, 5, 33, 320, DateTimeKind.Local).AddTicks(2592),
                            Email = "jane.smith@example.com",
                            EmailEnvoye = false,
                            EmailEnvoyeLivree = false,
                            NomCarte = "Mastercard",
                            NumCompte = "65432110223463790345",
                            NumTel = "87654321",
                            Statut = "EnPreparation",
                            TypeCarte = "National"
                        });
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AgenceId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Civilite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateDelivranceCIN")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateExpirationCIN")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EtatCivil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LieuDelivranceCIN")
                        .HasColumnType("longtext");

                    b.Property<string>("Nationalite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NiveauEducation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomMere")
                        .HasColumnType("longtext");

                    b.Property<string>("NomPere")
                        .HasColumnType("longtext");

                    b.Property<int>("NombreEnfants")
                        .HasColumnType("int");

                    b.Property<string>("NumCIN")
                        .HasColumnType("longtext");

                    b.Property<string>("PaysNaissance")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoClient")
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("RevenuMensuel")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SituationProfessionnelle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "123 Main St",
                            AgenceId = "67f6461d3d6e3c7fa3ef47ad",
                            Civilite = "M",
                            DateDelivranceCIN = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateExpirationCIN = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "guesmiimahmoud@gmail.com",
                            EtatCivil = "Célibataire",
                            Genre = "Masculin",
                            LieuDelivranceCIN = "New York",
                            Nationalite = "US",
                            NiveauEducation = "Master",
                            Nom = "Doe",
                            NomMere = "Jane Doe",
                            NomPere = "John Doe Sr.",
                            NombreEnfants = 2,
                            NumCIN = "14668061",
                            PaysNaissance = "USA",
                            PhotoClient = "mahmoud.jpg",
                            Prenom = "John",
                            Profession = "Ingénieur",
                            Residence = "New York",
                            RevenuMensuel = 5000.00m,
                            SituationProfessionnelle = "Employé",
                            Telephone = "123456789",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "456 Elm St",
                            AgenceId = "67f6461d3d6e3c7fa3ef47ae",
                            Civilite = "Mme",
                            DateDelivranceCIN = new DateTime(2015, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateExpirationCIN = new DateTime(2035, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            EtatCivil = "Marié(e)",
                            Genre = "Féminin",
                            LieuDelivranceCIN = "Toronto",
                            Nationalite = "CA",
                            NiveauEducation = "Doctorat",
                            Nom = "Smith",
                            NomMere = "Mary Smith",
                            NomPere = "Robert Smith",
                            NombreEnfants = 1,
                            NumCIN = "14668062",
                            PaysNaissance = "Canada",
                            PhotoClient = "mahmoud.jpg",
                            Prenom = "Jane",
                            Profession = "Médecin",
                            Residence = "Toronto",
                            RevenuMensuel = 7000.00m,
                            SituationProfessionnelle = "Indépendant",
                            Telephone = "987654321",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "456 ben arous",
                            AgenceId = "67f6461d3d6e3c7fa3ef47ae",
                            Civilite = "Mme",
                            DateDelivranceCIN = new DateTime(2013, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateExpirationCIN = new DateTime(2035, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robert.smith@example.com",
                            EtatCivil = "Marié(e)",
                            Genre = "Masculin",
                            LieuDelivranceCIN = "Toronto",
                            Nationalite = "TN",
                            NiveauEducation = "Doctorat",
                            Nom = "robert",
                            NomMere = "Mary Smith",
                            NomPere = "Robert Smith",
                            NombreEnfants = 1,
                            NumCIN = "19668067",
                            PaysNaissance = "Canada",
                            PhotoClient = "mahmoud.jpg",
                            Prenom = "smith",
                            Profession = "Médecin",
                            Residence = "Tunis",
                            RevenuMensuel = 2000.00m,
                            SituationProfessionnelle = "Indépendant",
                            Telephone = "997654321",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Compte", b =>
                {
                    b.Property<string>("RIB")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DecouvertAutorise")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MontantMaxAutoriseParJour")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("NbrOperationsAutoriseesParJour")
                        .HasColumnType("longtext");

                    b.Property<string>("NumCin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Solde")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("idAgent")
                        .HasColumnType("longtext");

                    b.HasKey("RIB");

                    b.HasIndex("ClientId");

                    b.ToTable("Comptes");

                    b.HasData(
                        new
                        {
                            RIB = "12345678923537902652",
                            ClientId = 1,
                            DateCreation = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IBAN = "TN2110500678923537952",
                            MontantMaxAutoriseParJour = 0m,
                            NumCin = "14668061",
                            Solde = 1000.50m,
                            Statut = "Actif",
                            Type = "Courant"
                        },
                        new
                        {
                            RIB = "65432110223463790345",
                            ClientId = 2,
                            DateCreation = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IBAN = "TN1210500110223463745",
                            MontantMaxAutoriseParJour = 0m,
                            NumCin = "14668062",
                            Solde = 5000.00m,
                            Statut = "Actif",
                            Type = "Epargne"
                        });
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AgenceId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Departement")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgenceId = "67f6461d3d6e3c7fa3ef47ad",
                            Departement = "Administration",
                            Nom = "Admin",
                            Prenom = "STB",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            AgenceId = "67f6461d3d6e3c7fa3ef47ae",
                            Departement = "Administration",
                            Nom = "Admin5",
                            Prenom = "STB5",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Beneficiaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RIBCompte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Beneficiaires");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Carte", b =>
                {
                    b.Property<string>("NumCarte")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodeCVV")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodePIN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompteRIB")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateRecuperation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Iddemande")
                        .HasColumnType("int");

                    b.Property<string>("Nature")
                        .HasColumnType("longtext");

                    b.Property<string>("NomCarte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PlafondDAP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PlafondTPE")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RIB")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Solde")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeCarte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NumCarte");

                    b.HasIndex("CompteRIB");

                    b.HasIndex("Iddemande");

                    b.HasIndex("RIB");

                    b.ToTable("Cartes");

                    b.HasData(
                        new
                        {
                            NumCarte = "1111222233334444",
                            CodeCVV = "",
                            CodePIN = "",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateExpiration = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Iddemande = 1,
                            Nature = "postpayee",
                            NomCarte = "VisaClassic",
                            PlafondDAP = 20000m,
                            PlafondTPE = 40000m,
                            RIB = "12345678923537902652",
                            Solde = 1000.50m,
                            Statut = "Active",
                            TypeCarte = "International"
                        },
                        new
                        {
                            NumCarte = "5555666677778888",
                            CodeCVV = "",
                            CodePIN = "",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateExpiration = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Iddemande = 2,
                            Nature = "postpayee",
                            NomCarte = "Mastercard",
                            PlafondDAP = 20000m,
                            PlafondTPE = 40000m,
                            RIB = "65432110223463790345",
                            Solde = 5000.00m,
                            Statut = "Active",
                            TypeCarte = "National"
                        });
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Chequier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateLivraison")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DemandeChequierId")
                        .HasColumnType("int");

                    b.Property<int?>("IdAgent")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DemandeChequierId");

                    b.ToTable("Chequiers");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.DemandeAugmentationPlafond", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CarteNumCarte")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateTraitement")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("NouveauPlafondDAB")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NouveauPlafondTPE")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumCarte")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Raison")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CarteNumCarte");

                    b.HasIndex("NumCarte");

                    b.ToTable("DemandesAugmentationPlafond");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.DemandeChequier", b =>
                {
                    b.Property<int>("IdDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("AccepteEngagement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AdresseComplete")
                        .HasColumnType("longtext");

                    b.Property<string>("CodePostal")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdAgent")
                        .HasColumnType("int");

                    b.Property<string>("ModeLivraison")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NombreFeuilles")
                        .HasColumnType("int");

                    b.Property<string>("NumTel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroChequier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Otp")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PlafondChequier")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("RaisonDemande")
                        .HasColumnType("longtext");

                    b.Property<string>("RibCompte")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isBarre")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdDemande");

                    b.HasIndex("RibCompte");

                    b.ToTable("DemandesChequiers");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.DemandeModificationDecouvert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DecouvertDemande")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("IdAgentRepondant")
                        .HasColumnType("int");

                    b.Property<bool>("MailEnvoyee")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MotifRefus")
                        .HasColumnType("longtext");

                    b.Property<bool>("NotificationEnvoyee")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RIBCompte")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StatutDemande")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RIBCompte");

                    b.ToTable("DemandeModificationDecouverts");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int");

                    b.Property<string>("Destinataire")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnvoye")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.FeuilleChequier", b =>
                {
                    b.Property<int>("IdFeuille")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DemandeChequierId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroFeuille")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PlafondFeuille")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("IdFeuille");

                    b.HasIndex("DemandeChequierId");

                    b.ToTable("FeuillesChequiers");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.FraisCarte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumCarte")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NumCarte");

                    b.ToTable("FraisCartes");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.FraisCompte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdsVirementsStr")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("RIB")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RIB");

                    b.ToTable("FraisComptes");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.PackElyssa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CDIContractPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("FrenchResidenceProofPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LongStayVisaPath")
                        .HasColumnType("longtext");

                    b.Property<string>("PassportPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SelectedAgency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TaxWithholdingCertificatePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VisaRegistrationPath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("PackElyssa");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.PackStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BoursePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("DomicileFrancePath")
                        .HasColumnType("longtext");

                    b.Property<string>("DomicileTunisiePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InscriptionPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PassportPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SelectedAgency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("PackStudents");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.PeriodeDecouvert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MontantMaxDecouvert")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("RIB")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("SoldeInitial")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("RIB");

                    b.ToTable("PeriodeDecouverts");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.RechargeCarte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CarteEmetteurNum")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("CarteRecepteurNum")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("DateRecharge")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Frais")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("Id");

                    b.HasIndex("CarteEmetteurNum");

                    b.HasIndex("CarteRecepteurNum");

                    b.ToTable("RechargesCarte");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Reclamation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdAgent")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Reponse")
                        .HasColumnType("longtext");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Reclamations");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "guesmiimahmoud@gmail.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$UsgGmUcvr/reX2vczXFtHeNFkDbhgr6o3D1KA8EQP00UA/xN6XVeW",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$.S6W9ANg3dgQ81TkO/GWVOCBnIa135ts5vY/aCAKXd0vp8G9ijCgu",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 4,
                            Email = "robert.smith@example.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$if9tkSXdV5FY2HpsK7/5LuQ.86G2h7Z42i5prPUEGy36z75XFM7hG",
                            Role = "Client"
                        },
                        new
                        {
                            Id = 3,
                            Email = "agent@stb.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$OJ2bjGVzZnRfw33YkI/pDu25fw0FguE3Zu9IpfpNysOtLwQ2IqYu.",
                            Role = "Agent"
                        },
                        new
                        {
                            Id = 5,
                            Email = "agent5@stb.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$XqsY2p2VxpXlmvWqIeeNpu0MmLnrUol3Oxsvis2JLE3iv9gPxYEhq",
                            Role = "Agent"
                        });
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Virement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateVirement")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FichierBeneficaires")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RIB_Emetteur")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RIB_Recepteur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeVirement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RIB_Emetteur", "DateVirement")
                        .IsUnique();

                    b.ToTable("Virements");
                });

            modelBuilder.Entity("DemandeCarte", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Compte", "Compte")
                        .WithMany("DemandesCarte")
                        .HasForeignKey("NumCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Client", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("STBEverywhere_Back_SharedModels.Client", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Compte", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Client", "Client")
                        .WithMany("Comptes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Agent", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("STBEverywhere_Back_SharedModels.Models.Agent", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Beneficiaire", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Client", "Client")
                        .WithMany("Beneficiaires")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Carte", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Compte", null)
                        .WithMany("Cartes")
                        .HasForeignKey("CompteRIB");

                    b.HasOne("DemandeCarte", "DemandeCarte")
                        .WithMany("Cartes")
                        .HasForeignKey("Iddemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STBEverywhere_Back_SharedModels.Compte", "Compte")
                        .WithMany()
                        .HasForeignKey("RIB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compte");

                    b.Navigation("DemandeCarte");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Chequier", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Models.DemandeChequier", "DemandeChequier")
                        .WithMany()
                        .HasForeignKey("DemandeChequierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeChequier");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.DemandeAugmentationPlafond", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Models.Carte", null)
                        .WithMany("DemandesAugmentation")
                        .HasForeignKey("CarteNumCarte");

                    b.HasOne("STBEverywhere_Back_SharedModels.Models.Carte", "Carte")
                        .WithMany()
                        .HasForeignKey("NumCarte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carte");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.DemandeChequier", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Compte", "Compte")
                        .WithMany()
                        .HasForeignKey("RibCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.DemandeModificationDecouvert", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Compte", "Compte")
                        .WithMany()
                        .HasForeignKey("RIBCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.EmailLog", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Models.DemandeChequier", "DemandeChequier")
                        .WithMany("Emails")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeChequier");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.FeuilleChequier", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Models.DemandeChequier", "DemandeChequier")
                        .WithMany("Feuilles")
                        .HasForeignKey("DemandeChequierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeChequier");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.FraisCarte", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Models.Carte", "Carte")
                        .WithMany("FraisCartes")
                        .HasForeignKey("NumCarte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carte");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.FraisCompte", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Compte", "Compte")
                        .WithMany("FraisComptes")
                        .HasForeignKey("RIB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.PackElyssa", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.PackStudent", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.PeriodeDecouvert", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Compte", "Compte")
                        .WithMany("PeriodesDecouvert")
                        .HasForeignKey("RIB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.RechargeCarte", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Models.Carte", "CarteEmetteur")
                        .WithMany()
                        .HasForeignKey("CarteEmetteurNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STBEverywhere_Back_SharedModels.Models.Carte", "CarteRecepteur")
                        .WithMany()
                        .HasForeignKey("CarteRecepteurNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarteEmetteur");

                    b.Navigation("CarteRecepteur");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Reclamation", b =>
                {
                    b.HasOne("STBEverywhere_Back_SharedModels.Client", "Client")
                        .WithMany("Reclamations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DemandeCarte", b =>
                {
                    b.Navigation("Cartes");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Client", b =>
                {
                    b.Navigation("Beneficiaires");

                    b.Navigation("Comptes");

                    b.Navigation("Reclamations");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Compte", b =>
                {
                    b.Navigation("Cartes");

                    b.Navigation("DemandesCarte");

                    b.Navigation("FraisComptes");

                    b.Navigation("PeriodesDecouvert");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.Carte", b =>
                {
                    b.Navigation("DemandesAugmentation");

                    b.Navigation("FraisCartes");
                });

            modelBuilder.Entity("STBEverywhere_Back_SharedModels.Models.DemandeChequier", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Feuilles");
                });
#pragma warning restore 612, 618
        }
    }
}
